url: https://wittenlab.com
enforce_ssl: wittenlab.com
permalink: /:categories/:title
sass:
    sass_dir: _scss
    style: compressed
    
title: Witten Lab
description: We make things as simple as possible.

superstring_title: Superstring
superstring_meta_title: Superstring - Lyric video editor
superstring_description: Superstring is a Mac & Windows app that lets you create lyric videos easily.
ko_superstring_meta_title: Superstring - 리릭 비디오 에디터
ko_superstring_description: Superstring은 멋진 리릭 비디오를 쉽게 만들 수 있는 Mac, Windows 앱입니다.

superstring:
    - updates:
      version: 3.2.6
      release_date: Jan 10, 2019
      mac: https://wittenlab.com/files/superstring/Superstring3.2.6.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring3.2.6.exe.zip
      contents:
      - content: Improves stability
      - content: Fixes minor issues
      contents_ko:
      - content: 안정성 개선
      - content: 사소한 오류 수정
    - updates:
      version: 3.2.4
      release_date: Nov 8, 2018
      mac: https://wittenlab.com/files/superstring/Superstring3.2.4.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring3.2.4.exe.zip
      contents:
      - content: Adds new "Teko", "Rasa" fonts
      - content: Fixes minor issues
      contents_ko:
      - content: 새로운 폰트 "Teko", "Rasa" 추가
      - content: 사소한 오류 수정
    - updates:
      version: 3.2.2
      release_date: Oct 1, 2018
      mac: https://wittenlab.com/files/superstring/Superstring3.2.2.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring3.2.2.exe.zip
      contents:
      - content: Adds "Appearance" in settings
      - content: Improves stability
      - content: Fixes minor issues
      contents_ko:
      - content: 화면 모드 설정 추가
      - content: 안정성 개선
      - content: 사소한 오류 수정
    - updates:
      version: 3.2.0
      release_date: Sep 4, 2018
      mac: https://wittenlab.com/files/superstring/Superstring3.2.0.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring3.2.0.exe.zip
      contents:
      - content: Adds a new "Direction Sign" text style
      - content: Removes the preview when exporting to increase performance
      - content: Removes the background color to increase performance
      - content: Improves stability
      - content: Fixes minor issues
      contents_ko:
      - content: 새로운 텍스트 스타일 "방향 표지판" 추가
      - content: 성능 향상을 위해 내보내기 시 미리보기 제거
      - content: 성능 향상을 위해 배경 색 제거
      - content: 안정성 개선
      - content: 사소한 오류 수정
    - updates:
      version: 3.1.6
      release_date: Aug 4, 2018
      mac: https://wittenlab.com/files/superstring/Superstring3.1.6.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring3.1.6.exe.zip
      contents:
      - content: Adds new "Bebas Neue" font
      - content: Adds a new "Ken Burns" text style
      - content: Improves usability
      - content: Fixes minor issues
      contents_ko:
      - content: 새로운 폰트 "Bebas Neue" 추가
      - content: 새로운 텍스트 스타일 "켄 번즈" 추가
      - content: 사용성 개선
      - content: 사소한 오류 수정
    - updates:
      version: 3.1.0
      release_date: Jul 20, 2018
      mac: https://wittenlab.com/files/superstring/Superstring3.1.0.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring3.1.0.exe.zip
      contents:
      - content: Adds a new "Dissolve & Scale" text style
      - content: Wide preview screen
      - content: Improves performance
      - content: Improves stability
      - content: Fixes minor issues
      contents_ko:
      - content: 텍스트 스타일 "Dissolve & Scale" 추가
      - content: 넓어진 미리보기 화면
      - content: 작업 성능 개선
      - content: 안정성 개선
      - content: 사소한 오류 수정
    - updates:
      version: 3.0.0
      release_date: Jul 1, 2018
      mac: https://wittenlab.com/files/superstring/Superstring3.0.0.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring3.0.0.exe.zip
      contents:
      - content: Adds beautiful, free photos
      - content: Adds more effects
      - content: Adds new fonts
      - content: Support .wav format
      - content: Improves performance
      - content: Improves stability
      - content: Fixes minor issues
      contents_ko:
      - content: 무료 이미지 라이브러리 추가
      - content: 새로운 효과 추가
      - content: 새로운 글꼴 추가
      - content: .wav 형식 지원
      - content: 작업 성능 개선
      - content: 안정성 개선
      - content: 사소한 오류 수정

superstring_showcase:
    - youtube: gzI2GOkR9E0
      song: Revolution ting
      artist: Black The Ripper
    - youtube: DtiB-L9EVlY
      song: Ultraspell
      artist: Strange Fiction
    - youtube: 5anAxF5V6vw
      song: Trust Alone
      artist: Shane Lother
    - youtube: kY11hwuI8Zc
      song: The purge in pallet town
      artist: Robotface
    - youtube: C-zWqiQx06g
      song: Bottle of Whiskey & A Razor Blade
      artist: Liminal Music
    - youtube: hwcci1Ysxiw
      song: All Hope Is Gone
      artist: Paul Miro
    - youtube: 1KHxxRBfm-4
      song: New
      artist: The Brothers Cole
    - youtube: UjIrASHfU-8
      song: Aku Bunuh Kamu Berkali
      artist: Scarlet Lady
    - youtube: FTOt23saVPM
      song: Better Than The Best
      artist: Nation In Blue

membrane_title: Membrane
membrane_meta_title: Membrane - Cover image editor
membrane_description: Membrane is a Mac & Windows app that lets you create your cover images easily.
ko_membrane_meta_title: Membrane - 커버 이미지 에디터
ko_membrane_description: Membrane은 커버 이미지를 쉽게 만들 수 있는 Mac, Windows 앱입니다.

membrane:
    - updates:
      version: 2.2.0
      release_date: Nov 8, 2018
      mac: https://wittenlab.com/files/membrane/Membrane2.2.0.app.zip
      windows: https://wittenlab.com/files/membrane/Membrane2.2.0.exe.zip
      contents: 
      - content: Adds new "Teko", "Rasa" fonts
      - content: Fixes minor issues
      contents_ko:
      - content: 새로운 폰트 "Teko", "Rasa" 추가
      - content: 사소한 오류 수정
    - updates:
      version: 2.1.8
      release_date: Oct 1, 2018
      mac: https://wittenlab.com/files/membrane/Membrane2.1.8.app.zip
      windows: https://wittenlab.com/files/membrane/Membrane2.1.8.exe.zip
      contents: 
      - content: Adds "Appearance" in settings
      - content: Improves usability
      - content: Fixes minor issues
      contents_ko:
      - content: 화면 모드 설정 추가
      - content: 사용성 개선
      - content: 사소한 오류 수정
    - updates:
      version: 2.1.5
      release_date: Aug 4, 2018
      mac: https://wittenlab.com/files/membrane/Membrane2.1.5.app.zip
      windows: https://wittenlab.com/files/membrane/Membrane2.1.5.exe.zip
      contents: 
      - content: Adds new "Bebas Neue" font
      - content: Improves usability
      - content: Fixes minor issues
      contents_ko:
      - content: 새로운 폰트 "Bebas Neue" 추가
      - content: 사용성 개선
      - content: 사소한 오류 수정
    - updates:
      version: 2.0.0
      release_date: Jul 1, 2018
      mac: https://wittenlab.com/files/membrane/Membrane2.0.0.app.zip
      windows: https://wittenlab.com/files/membrane/Membrane2.0.0.exe.zip
      contents: 
      - content: Adds beautiful, free photos
      - content: Adds more templates
      - content: Adds new fonts
      - content: Improves performance
      - content: Improves stability
      - content: Fixes minor issues
      contents_ko:
      - content: 무료 이미지 라이브러리 추가
      - content: 새로운 템플릿 추가
      - content: 새로운 글꼴 추가
      - content: 작업 성능 개선
      - content: 안정성 개선
      - content: 사소한 오류 수정

membrane_showcase:
    - url: assets/img/superstring/facebook.png
      title: Facebook cover
      artist: Witten Lab