url: https://wittenlab.com
enforce_ssl: wittenlab.com
permalink: /:categories/:title
sass:
  sass_dir: _scss
  style: compressed

title: Witten Lab
description: We make things as simple as possible.
youtube: https://www.youtube.com/c/wittenlab
facebook: https://www.facebook.com/wittenlab
instagram: https://www.instagram.com/wittenlab
cloudinary: https://res.cloudinary.com/wittenlab/image/upload/q_auto,f_auto,dpr_auto

superstring:
  title: Superstring
  price: $69.99
  meta_title: Superstring - Lyric video maker
  description: Superstring is a Mac & Windows app that lets you create lyric videos easily.
  meta_title_ko: Superstring - 리릭 비디오 제작 툴
  description_ko: Superstring은 멋진 리릭 비디오를 쉽게 만들 수 있는 Mac, Windows 앱입니다.
  versions:
  - version:
    versionNumber: 2020.11.29
    release_date: Nov 29, 2020
    mac: https://wittenlab.com/files/superstring/Superstring2020.11.29.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring2020.11.29.exe.zip
    updates:
      - update: You can use Pexels video library.
      - update: New text styles “Chromatic Aberration”, “Pop” have been added.
      - update: The rendering quality has been improved.
      - update: Minor issues have been fixed.
    updates_ko:
      - update: Pexels 비디오 라이브러리를 사용할 수 있습니다.
      - update: “색수차”, “팝” 텍스트 스타일이 추가되었습니다.
      - update: 랜더링 품질이 향상되었습니다.
      - update: 사소한 오류들이 수정되었습니다.
  - version:
    versionNumber: 2020.7.19
    release_date: Jul 19, 2020
    mac: https://wittenlab.com/files/superstring/Superstring2020.7.19.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring2020.7.19.exe.zip
    updates:
    - update: You can align the timing of clips easily with the timestamp button.
    - update: You can add a border and a shadow to the text.
    - update: New font “Baloo”, “Jaldi” and “Lab Digital” has been added.
    - update: The usability of the editor has been improved.
    - update: Minor issues have been fixed.
    updates_ko:
    - update: 타임스탬프 버튼으로 가사의 타이밍을 쉽게 맞출 수 있습니다.
    - update: 텍스트에 테두리와 그림자를 적용할 수 있습니다.
    - update: 새로운 폰트 “Baloo”, “Jaldi”, “LAB디지털”이 추가되었습니다.
    - update: 에디터의 사용성이 개선되었습니다.
    - update: 사소한 오류들이 수정되었습니다.
  - version:
    versionNumber: 2020.6.21
    release_date: Jun 21, 2020
    mac: https://wittenlab.com/files/superstring/Superstring2020.6.21.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring2020.6.21.exe.zip
    updates:
    - update: You can add background videos.
    - update: You can apply “3D rotation” to the text.
    - update: New text styles “Cover”, “Cube”, “Stamp”, “Uncover” have been added.
    - update: New font group “Rounded” has been added.
    - update: New fonts have been added.
    - update: The rendering quality has been improved.
    - update: The usability of the editor has been improved.
    - update: Minor issues have been fixed.
    updates_ko:
    - update: 배경에 비디오를 추가할 수 있습니다.
    - update: 텍스트에 “3D 회전”을 적용할 수 있습니다.
    - update: ”덮기”, “큐브”, “스탬프”, “당기기” 텍스트 스타일이 추가되었습니다.
    - update: “라운드“ 폰트 그룹이 추가되었습니다.
    - update: 새로운 폰트들이 추가되었습니다.
    - update: 랜더링 품질이 향상되었습니다.
    - update: 에디터의 사용성이 개선되었습니다.
    - update: 사소한 오류들이 수정되었습니다.
  - versions:
    versionNumber: 3.9.3
    release_date: Mar 1, 2020
    mac: https://wittenlab.com/files/superstring/Superstring3.9.3.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.9.3.exe.zip
    updates:
    - update: Adds a new “Canvas” feature
    - update: Adds a new “Frame” background style
    - update: Adds new “Blur”, “Pulse” background options
    - update: Adds a new “Damion” font
    - update: Improves the editor usability
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 기능 “캔버스” 추가
    - update: 새로운 백그라운드 스타일 “프레임” 추가
    - update: 새로운 백그라운드 옵션 “블러”, “펄스” 추가
    - update: 새로운 폰트 “Damion” 추가
    - update: 에디터 사용성 개선
    - update: 사소한 오류 수정
  - versions:
    versionNumber: 3.8.5
    release_date: Jan 15, 2020
    mac: https://wittenlab.com/files/superstring/Superstring3.8.5.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.8.5.exe.zip
    updates:
    - update: Adds new “Girassol”, “Righteous”, “Underwood Champion” fonts
    - update: Adds a “Pin sidebar” option in the settings
    - update: Improves the menu bar
    - update: Improves stability
    - update: Performance increase
    updates_ko:
    - update: 새로운 폰트 “Girassol”, “Righteous”, “Underwood Champion” 추가
    - update: 셋팅에 “사이드바 고정” 옵션 추가
    - update: 메뉴 바 사용성 개선
    - update: 안정성 개선
    - update: 작업 성능 향상
  - versions:
    versionNumber: 3.7.4
    release_date: Dec 20, 2019
    mac: https://wittenlab.com/files/superstring/Superstring3.7.4.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.7.4.exe.zip
    updates:
    - update: Adds a new “Blur” text & background style
    - update: Wide text area
    - update: Improves stability
    - update: Performance increase
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 텍스트 & 백그라운드 스타일 “블러” 추가
    - update: 넓어진 텍스트 영역
    - update: 안정성 개선
    - update: 작업 성능 향상
    - update: 사소한 오류 수정
  - versions:
    versionNumber: 3.6.8
    release_date: Oct 8, 2019
    mac: https://wittenlab.com/files/superstring/Superstring3.6.8.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.6.8.exe.zip
    updates:
    - update: Adds a new “Gmarket Sans” font
    - update: Adds new “Acceleration”, “Rotation” options
    - update: Improves the editor usability
    - update: Improves stability
    updates_ko:
    - update: 새로운 폰트 “지마켓 산스” 추가
    - update: 새로운 옵션 “가속”, “회전” 추가
    - update: 에디터 사용성 개선
    - update: 안정성 개선
  - versions:
    versionNumber: 3.3.6
    release_date: Jul 1, 2019
    mac: https://wittenlab.com/files/superstring/Superstring3.3.6.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.3.6.exe.zip
    updates:
    - update: Adds a zoom feature to the editor
    - update: Improves video quality
    - update: Fixes minor issues
    updates_ko:
    - update: 에디터 줌 기능 추가
    - update: 비디오 화질 개선
    - update: 사소한 오류 수정
  - versions:
    versionNumber: 3.3.0
    release_date: May 12, 2019
    mac: https://wittenlab.com/files/superstring/Superstring3.3.0.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.3.0.exe.zip
    updates:
    - update: Adds new “Abyssinica”, “Fondamento”, “Uncial Antiqua” fonts
    - update: Removes “Seoul Hangang”, “Seoul Namsan” fonts due to memory problems
    - update: Improves stability
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 폰트 “Abyssinica”, “Fondamento”, “Uncial Antiqua” 추가
    - update: 메모리 문제로 인해 “Seoul Hangang”, “Seoul Namsan” 폰트 삭제
    - update: 안정성 개선
    - update: 사소한 오류 수정
  - versions:
    versionNumber: 3.2.8
    release_date: Mar 1, 2019
    mac: https://wittenlab.com/files/superstring/Superstring3.2.8.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.2.8.exe.zip
    updates:
    - update: Adds a new “GFS Neohellenic” font
    - update: Improves stability
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 폰트 “GFS Neohellenic” 추가
    - update: 안정성 개선
    - update: 사소한 오류 수정
  - versions:
    versionNumber: 3.2.4
    release_date: Nov 8, 2018
    mac: https://wittenlab.com/files/superstring/Superstring3.2.4.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.2.4.exe.zip
    updates:
    - update: Adds new “Teko”, “Rasa” fonts
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 폰트 “Teko”, “Rasa” 추가
    - update: 사소한 오류 수정
  - versions:
    versionNumber: 3.2.0
    release_date: Sep 4, 2018
    mac: https://wittenlab.com/files/superstring/Superstring3.2.0.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.2.0.exe.zip
    updates:
    - update: Adds a new “Direction Sign” text style
    - update: Removes the preview when exporting to increase performance
    - update: Removes the background color to increase performance
    - update: Improves stability
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 텍스트 스타일 “방향 표지판” 추가
    - update: 성능 향상을 위해 내보내기 시 미리보기 제거
    - update: 성능 향상을 위해 배경 색 제거
    - update: 안정성 개선
    - update: 사소한 오류 수정
  - versions:
    versionNumber: 3.1.6
    release_date: Aug 4, 2018
    mac: https://wittenlab.com/files/superstring/Superstring3.1.6.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.1.6.exe.zip
    updates:
    - update: Adds new “Bebas Neue” font
    - update: Adds new “Dissolve” and “Ken Burns” text styles
    - update: Improves performance
    - update: Improves usability
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 폰트 “Bebas Neue” 추가
    - update: 새로운 텍스트 스타일 "디졸브", “켄 번즈” 추가
    - update: 작업 성능 개선
    - update: 사용성 개선
    - update: 사소한 오류 수정
  - versions:
    versionNumber: 3.0.0
    release_date: Jul 1, 2018
    mac: https://wittenlab.com/files/superstring/Superstring3.0.0.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring3.0.0.exe.zip
    updates:
    - update: Adds beautiful, free photos
    - update: Adds more effects
    - update: Adds new fonts
    - update: Supports .wav format
    - update: Improves performance
    - update: Improves stability
    - update: Fixes minor issues
    updates_ko:
    - update: 무료 이미지 라이브러리 추가
    - update: 새로운 효과 추가
    - update: 새로운 글꼴 추가
    - update: .wav 형식 지원
    - update: 작업 성능 개선
    - update: 안정성 개선
    - update: 사소한 오류 수정
  - versions:
    versionNumber: 2.9.91
    release_date: Mar 28, 2018
    mac: https://wittenlab.com/files/superstring/Superstring2.9.91.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring2.9.91.exe.zip
    updates:
      - update: Improves stability
      - update: Fixes minor issues
    updates_ko:
      - update: 안정성 개선
      - update: 사소한 오류 수정

membrane:
  title: Membrane
  price: $69.99
  meta_title: Membrane - Album artwork maker
  description: Membrane is a Mac & Windows app that lets you create album artworks easily.
  meta_title_ko: Membrane - 앨범 아트웍 제작 툴
  description_ko: Membrane은 앨범 아트웍을 쉽게 만들 수 있는 Mac, Windows 앱입니다.
  versions:
  - version:
    versionNumber: 2020.9.12
    release_date: Sep 12, 2020
    mac: https://wittenlab.com/files/membrane/Membrane2020.9.12.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2020.9.12.exe.zip
    updates:
    - update: You can use Pexels image library.
    - update: New font “Baloo”, “Jaldi” and “Lab Digital” has been added.
    - update: The usability of the editor has been improved.
    - update: Minor issues have been fixed.
    updates_ko:
    - update: Pexels 이미지 라이브러리를 사용할 수 있습니다.
    - update: 새로운 폰트 “Baloo”, “Jaldi”, “LAB디지털”이 추가되었습니다.
    - update: 에디터의 사용성이 개선되었습니다.
    - update: 사소한 오류들이 수정되었습니다.
  - version:
    versionNumber: 2020.6.21
    release_date: Jun 21, 2020
    mac: https://wittenlab.com/files/membrane/Membrane2020.6.21.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2020.6.21.exe.zip
    updates:
    - update: New fonts have been added.
    - update: The usability of the editor has been improved.
    - update: Minor issues have been fixed.
    updates_ko:
    - update: 새로운 폰트들이 추가되었습니다.
    - update: 에디터의 사용성이 개선되었습니다.
    - update: 사소한 오류들이 수정되었습니다.
  - version:
    versionNumber: 2.3.0
    release_date: May 12, 2019
    mac: https://wittenlab.com/files/membrane/Membrane2.3.0.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.3.0.exe.zip
    updates:
    - update: Adds new “Abyssinica”, “Fondamento”, “Uncial Antiqua” fonts
    - update: Removes “Seoul Hangang”, “Seoul Namsan” fonts due to memory problems
    - update: Improves stability
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 폰트 “Abyssinica”, “Fondamento”, “Uncial Antiqua” 추가
    - update: 메모리 문제로 인해 “Seoul Hangang”, “Seoul Namsan” 폰트 삭제
    - update: 안정성 개선
    - update: 사소한 오류 수정
  - version:
    versionNumber: 2.2.0
    release_date: Nov 8, 2018
    mac: https://wittenlab.com/files/membrane/Membrane2.2.0.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.2.0.exe.zip
    updates:
    - update: Adds new “Teko”, “Rasa” fonts
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 폰트 “Teko”, “Rasa” 추가
    - update: 사소한 오류 수정
  - version:
    versionNumber: 2.1.5
    release_date: Aug 4, 2018
    mac: https://wittenlab.com/files/membrane/Membrane2.1.5.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.1.5.exe.zip
    updates:
    - update: Adds new “Bebas Neue” font
    - update: Improves usability
    - update: Fixes minor issues
    updates_ko:
    - update: 새로운 폰트 “Bebas Neue” 추가
    - update: 사용성 개선
    - update: 사소한 오류 수정
  - version:
    versionNumber: 2.0.0
    release_date: Jul 1, 2018
    mac: https://wittenlab.com/files/membrane/Membrane2.0.0.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.0.0.exe.zip
    updates:
    - update: Adds beautiful, free photos
    - update: Adds more templates
    - update: Adds new fonts
    - update: Improves performance
    - update: Improves stability
    - update: Fixes minor issues
    updates_ko:
    - update: 무료 이미지 라이브러리 추가
    - update: 새로운 템플릿 추가
    - update: 새로운 글꼴 추가
    - update: 작업 성능 개선
    - update: 안정성 개선
    - update: 사소한 오류 수정
  - version:
    versionNumber: 1.3.0
    release_date: Mar 28, 2018
    mac: https://wittenlab.com/files/membrane/Membrane1.3.0.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane1.3.0.exe.zip
    updates:
      - update: Improves stability
      - update: Fixes minor issues
    updates_ko:
      - update: 안정성 개선
      - update: 사소한 오류 수정