url: https://wittenlab.com
enforce_ssl: wittenlab.com
permalink: /:categories/:title
sass:
  sass_dir: _scss
  style: compressed

title: Witten Lab
description: We make things as simple as possible.
youtube: https://www.youtube.com/c/wittenlab
facebook: https://www.facebook.com/wittenlab
instagram: https://www.instagram.com/wittenlab
cloudinary: https://res.cloudinary.com/wittenlab/image/upload/q_auto,f_auto,dpr_auto

superstring:
  title: Superstring
  price: $69.99
  meta_title: Superstring - Lyric video maker
  description: Superstring is a Mac & Windows app that lets you create lyric videos easily.
  meta_title_ko: Superstring - 리릭 비디오 제작 툴
  description_ko: Superstring은 멋진 리릭 비디오를 쉽게 만들 수 있는 Mac, Windows 앱입니다.
  latest_version:
    version: 2020.7.19
    release_date: Jul 19, 2020
    mac: https://wittenlab.com/files/superstring/Superstring2020.7.19.app.zip
    windows: https://wittenlab.com/files/superstring/Superstring2020.7.19.exe.zip
    updates:
      - item: You can align the timing of clips easily with the timestamp button.
      - item: You can add a border and a shadow to the text.
      - item: New font “Baloo”, “Jaldi” and “Lab Digital” has been added.
      - item: The usability of the editor has been improved.
      - item: Minor issues have been fixed.
    updates_ko:
      - item: 타임스탬프 버튼으로 가사의 타이밍을 쉽게 맞출 수 있습니다.
      - item: 텍스트에 테두리와 그림자를 적용할 수 있습니다.
      - item: 새로운 폰트 “Baloo”, “Jaldi”, “LAB디지털”이 추가되었습니다.
      - item: 에디터의 사용성이 개선되었습니다.
      - item: 사소한 오류들이 수정되었습니다.

membrane:
  title: Membrane
  price: $69.99
  meta_title: Membrane - Album artwork maker
  description: Membrane is a Mac & Windows app that lets you create album artworks easily.
  meta_title_ko: Membrane - 앨범 아트웍 제작 툴
  description_ko: Membrane은 앨범 아트웍을 쉽게 만들 수 있는 Mac, Windows 앱입니다.

membrane_updates:
  - versions:
    version: 2020.6.21
    release_date: Jun 21, 2020
    mac: https://wittenlab.com/files/membrane/Membrane2020.6.21.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2020.6.21.exe.zip
    updates:
      - item: New fonts have been added.
      - item: The usability of the editor has been improved.
      - item: Minor issues have been fixed.
    updates_ko:
      - item: 새로운 폰트들이 추가되었습니다.
      - item: 에디터의 사용성이 개선되었습니다.
      - item: 사소한 오류들이 수정되었습니다.
  - versions:
    version: 2.3.0
    release_date: May 12, 2019
    mac: https://wittenlab.com/files/membrane/Membrane2.3.0.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.3.0.exe.zip
    updates:
      - item: Adds new “Abyssinica”, “Fondamento”, “Uncial Antiqua” fonts
      - item: Removes “Seoul Hangang”, “Seoul Namsan” fonts due to memory problems
      - item: Improves stability
      - item: Fixes minor issues
    updates_ko:
      - item: 새로운 폰트 “Abyssinica”, “Fondamento”, “Uncial Antiqua” 추가
      - item: 메모리 문제로 인해 “Seoul Hangang”, “Seoul Namsan” 폰트 삭제
      - item: 안정성 개선
      - item: 사소한 오류 수정
  - versions:
    version: 2.2.3
    release_date: Mar 1, 2019
    mac: https://wittenlab.com/files/membrane/Membrane2.2.3.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.2.3.exe.zip
    updates:
      - item: Adds new “GFS Neohellenic” font
      - item: Improves stability
      - item: Fixes minor issues
    updates_ko:
      - item: 새로운 폰트 “GFS Neohellenic” 추가
      - item: 안정성 개선
      - item: 사소한 오류 수정
  - versions:
    version: 2.2.0
    release_date: Nov 8, 2018
    mac: https://wittenlab.com/files/membrane/Membrane2.2.0.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.2.0.exe.zip
    updates:
      - item: Adds new “Teko”, “Rasa” fonts
      - item: Fixes minor issues
    updates_ko:
      - item: 새로운 폰트 “Teko”, “Rasa” 추가
      - item: 사소한 오류 수정
  - versions:
    version: 2.1.8
    release_date: Oct 1, 2018
    mac: https://wittenlab.com/files/membrane/Membrane2.1.8.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.1.8.exe.zip
    updates:
      - item: Adds “Appearance” in settings
      - item: Improves usability
      - item: Fixes minor issues
    updates_ko:
      - item: 화면 모드 설정 추가
      - item: 사용성 개선
      - item: 사소한 오류 수정
  - versions:
    version: 2.1.5
    release_date: Aug 4, 2018
    mac: https://wittenlab.com/files/membrane/Membrane2.1.5.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.1.5.exe.zip
    updates:
      - item: Adds new “Bebas Neue” font
      - item: Improves usability
      - item: Fixes minor issues
    updates_ko:
      - item: 새로운 폰트 “Bebas Neue” 추가
      - item: 사용성 개선
      - item: 사소한 오류 수정
  - versions:
    version: 2.0.0
    release_date: Jul 1, 2018
    mac: https://wittenlab.com/files/membrane/Membrane2.0.0.app.zip
    windows: https://wittenlab.com/files/membrane/Membrane2.0.0.exe.zip
    updates:
      - item: Adds beautiful, free photos
      - item: Adds more templates
      - item: Adds new fonts
      - item: Improves performance
      - item: Improves stability
      - item: Fixes minor issues
    updates_ko:
      - item: 무료 이미지 라이브러리 추가
      - item: 새로운 템플릿 추가
      - item: 새로운 글꼴 추가
      - item: 작업 성능 개선
      - item: 안정성 개선
      - item: 사소한 오류 수정