url: https://wittenlab.com
enforce_ssl: wittenlab.com
permalink: /:categories/:title
sass:
  sass_dir: _scss
  style: compressed

title: Witten Lab
description: We make things as simple as possible.
youtube: https://www.youtube.com/c/wittenlab
facebook: https://www.facebook.com/wittenlab
instagram: https://www.instagram.com/wittenlab

subscription: https://script.google.com/a/macros/wittenlab.com/s/AKfycby1ECiw2eMp9hsbAhWOxxCedo0vCDY1OL4rubzxAE5c_8T_vB7QydLKZhNEnoM6NEL_ig/exec

superstring:
  title: Superstring
  price: $99
  meta_title: Superstring - Lyric video maker
  description: Superstring is a Mac & Windows app that lets you create lyric videos easily.
  meta_title_ko: Superstring - 리릭 비디오 제작 툴
  description_ko: Superstring은 멋진 리릭 비디오를 쉽게 만들 수 있는 Mac, Windows 앱입니다.
  versions:
    - version:
      versionNumber: 2023.8.1
      release_date: Aug 1, 2023
      mac: https://wittenlab.com/files/superstring/Superstring2023.8.1.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring2023.8.1.exe.zip
      updates:
        - update: The usability of the user interface has been improved.
        - update: Overall stability has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: UI의 사용성이 개선되었습니다.
        - update: 전반적인 안정성이 향상되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2023.7.2
      release_date: Jul 2, 2023
      mac: https://wittenlab.com/files/superstring/Superstring2023.7.2.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring2023.7.2.exe.zip
      updates:
        - update: New effect option “Pulse” has been added.
        - update: New Background option “Color” has been added.
        - update: Implemented support for vertical video.
        - update: The usability of the user interface has been improved.
      updates_ko:
        - update: 새로운 효과 옵션 ”펄스”가 추가되었습니다.
        - update: 새로운 배경 옵션 ”색상”이 추가되었습니다.
        - update: 세로 동영상을 지원합니다.
        - update: UI의 사용성이 개선되었습니다.
    - version:
      versionNumber: 2023.5.1
      release_date: May 1, 2023
      mac: https://wittenlab.com/files/superstring/Superstring2023.5.1.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring2023.5.1.exe.zip
      updates:
        - update: New effect options “Color”, “Capacity“ have been added.
        - update: Overall performance has been improved.
        - update: The usability of the user interface has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: 새로운 효과 옵션 ”색상”, “수량”이 추가되었습니다.
        - update: 전반적인 성능이 향상되었습니다.
        - update: UI의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2023.2.25
      release_date: Feb 25, 2023
      mac: https://wittenlab.com/files/superstring/Superstring2023.2.25.app.zip
      windows: https://wittenlab.com/files/superstring/Superstring2023.2.25.exe.zip
      updates:
        - update: New effect styles “Black Hole”, “Fire“, “Spangles” have been added.
        - update: You can change an audio file easily.
        - update: Overall stability has been improved.
        - update: The usability of the editor has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: 새로운 효과 스타일 “블랙홀“, “불“, “스팽글”이 추가되었습니다.
        - update: 오디오 파일을 쉽게 변경할 수 있습니다.
        - update: 전반적인 안정성이 향상되었습니다.
        - update: 에디터의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2022.12.16
      release_date: Dec 16, 2022
      mac: https://drive.google.com/file/d/1BWhfimgOLwkrJWiY7TpRXGIUDeJkLTMD
      windows: https://drive.google.com/file/d/1BWd3igIk6dmpryxtuA7AR0stg7E15zLn
      updates:
        - update: You can use your device fonts.
        - update: New Acceleration styles “Bounce”, “Elastic” have been added.
        - update: The usability of the editor has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: 컴퓨터에 설치된 폰트를 사용할 수 있습니다.
        - update: 새로운 가속 스타일 “Bounce”, “Elastic”이 추가되었습니다.
        - update: 에디터의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2022.9.12
      release_date: Sep 12, 2022
      mac: https://drive.google.com/file/d/1BY8sNPj3_J1XI1EvDJpLbPttB7Rc04FK
      windows: https://drive.google.com/file/d/1BXT3gVNrgoFYzEARjtQxOL5uYrh4tEH2
      updates:
        - update: New effect styles “Camera Flash”, “Dust”, “Embers”, ”Glitter” have been added.
        - update: The usability of the editor has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: 새로운 효과 스타일 “카메라 플래시”, “먼지”, “불씨”, "반짝반짝"이 추가되었습니다.
        - update: 에디터의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2022.3.30
      release_date: Mar 30, 2022
      mac: https://drive.google.com/file/d/1BWlQ-3kTHQgPzVaTCvPK6Rx10c9J5hOD
      windows: https://drive.google.com/file/d/1BY7Wc_mXfyZ4PaAQqw_vMMwc-3T_2n8B
      updates:
        - update: You can adjust the video length.
        - update: You can move an audio clip.
        - update: Implemented support for Apple silicon(M1) Mac computers.
        - update: The usability of the editor has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: 영상의 길이를 조절할 수 있습니다.
        - update: 오디오 클립을 이동할 수 있습니다.
        - update: Apple 실리콘(M1) Mac 컴퓨터를 지원합니다.
        - update: 에디터의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2021.10.21
      release_date: Oct 21, 2021
      mac: https://drive.google.com/file/d/1jKyrIw_lATmcKM3W_B-6P0XR27kHouWC
      windows: https://drive.google.com/file/d/1jDJ7hnW2BCWR-xwnk2LGteAbY8PSX-Wx
      updates:
        - update: New font “Padauk“, “Rampart One“ has been added.
        - update: Overall stability has been improved.
        - update: The usability of the editor has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: 새로운 폰트 “Padauk“, “Rampart One“이 추가되었습니다.
        - update: 전반적인 안정성이 향상되었습니다.
        - update: 에디터의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2021.5.30
      release_date: May 30, 2021
      mac: https://drive.google.com/file/d/1j7inSXivchnMsa-qbL0TwxX09wkY3_fc
      windows: https://drive.google.com/file/d/1jIfL3yxW-MsV3atFC5FfhcvijCeO2ToU
      updates:
        - update: New effect styles “Rain”, “Snow”, “Starfield” have been added.
        - update: New font “Bungee“, “Londrina“, “Rajdhani“ has been added.
        - update: You can apply “Background Color” to the text.
        - update: The usability of the editor has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: 새로운 효과 스타일 “비”, “눈”, “우주”이 추가되었습니다.
        - update: 새로운 폰트 “Bungee“, “Londrina“, “Rajdhani“가 추가되었습니다.
        - update: 텍스트에 “배경 색상”을 적용할 수 있습니다.
        - update: 에디터의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2021.2.8
      release_date: FEb 8, 2021
      mac: https://drive.google.com/file/d/1jAH-M5AOrc7Ar4W8WnOW4Rpj5oRAMtIv
      windows: https://drive.google.com/file/d/1jL0Im-N2KyZXJ_vUpYhO1CteqTtC6iek
      updates:
        - update: You can export your Superstring data as .lrc or .srt.
        - update: You can apply “Skew” to the text.
        - update: New font “Lacquer“, “Sedgwick Ave” has been added.
        - update: The usability of the editor has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: Superstring 데이터를 .lrc 또는 .srt 파일로 내보낼 수 있습니다.
        - update: 텍스트에 “기울리기”를 적용할 수 있습니다.
        - update: 새로운 폰트 “Lacquer“, “Sedgwick Ave”이 추가되었습니다.
        - update: 에디터의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2020.11.29
      release_date: Nov 29, 2020
      mac: https://drive.google.com/file/d/1jFZVnnTTYIouIEz-cfE5iRnENPSisrn_
      windows: https://drive.google.com/file/d/1jIuawUkYIZKEtzO-T8-gIeZ15RCldEVz
      updates:
        - update: You can use Pexels video library.
        - update: New text styles “Chromatic Aberration”, “Pop” have been added.
        - update: The rendering quality has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: Pexels 비디오 라이브러리를 사용할 수 있습니다.
        - update: “색수차”, “팝” 텍스트 스타일이 추가되었습니다.
        - update: 랜더링 품질이 향상되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2020.7.19
      release_date: Jul 19, 2020
      mac: https://drive.google.com/file/d/1jIa3_lWni7Ufg5ahtaPTygGlyUwxHYWZ
      windows: https://drive.google.com/file/d/1jEukDkUx2yqgJestcfQLCRH1zYASfM6_
      updates:
        - update: You can align the timing of clips easily with the timestamp button.
        - update: You can add a border and a shadow to the text.
        - update: New font “Baloo”, “Jaldi” and “Lab Digital” has been added.
        - update: The usability of the editor has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: 타임스탬프 버튼으로 가사의 타이밍을 쉽게 맞출 수 있습니다.
        - update: 텍스트에 테두리와 그림자를 적용할 수 있습니다.
        - update: 새로운 폰트 “Baloo”, “Jaldi”, “LAB디지털”이 추가되었습니다.
        - update: 에디터의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
    - version:
      versionNumber: 2020.6.21
      release_date: Jun 21, 2020
      mac: https://drive.usercontent.google.com/download?id=1j7YpqAuX8VxPI9gdibWMkWsmD6_U9Kh4
      windows: https://drive.usercontent.google.com/download?id=1j9qVBu8AkqXqoThhxCRh1OvQHnfecUr-
      updates:
        - update: You can add background videos.
        - update: You can apply “3D rotation” to the text.
        - update: New text styles “Cover”, “Cube”, “Stamp”, “Uncover” have been added.
        - update: New font group “Rounded” has been added.
        - update: New fonts have been added.
        - update: The rendering quality has been improved.
        - update: The usability of the editor has been improved.
        - update: Minor issues have been fixed.
      updates_ko:
        - update: 배경에 비디오를 추가할 수 있습니다.
        - update: 텍스트에 “3D 회전”을 적용할 수 있습니다.
        - update: ”덮기”, “큐브”, “스탬프”, “당기기” 텍스트 스타일이 추가되었습니다.
        - update: “라운드“ 폰트 그룹이 추가되었습니다.
        - update: 새로운 폰트들이 추가되었습니다.
        - update: 랜더링 품질이 향상되었습니다.
        - update: 에디터의 사용성이 개선되었습니다.
        - update: 사소한 오류들이 수정되었습니다.
